### ISSUE TITLE
Macros for Hints

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#19]
@davidfarmer : set hint links as an "exponent" with label as "hint", when expanded, in-text/bubble, with label "Hint:"

@Pelonza use a more consistent "hint" format in latex, perhaps as an explicit macro.\

Other hint issues:
extra space/line near hints. see 3.5.4
hint for 3.6.5 didn't parse right

**Comment by davidfarmer** [comment]
We need to decide how to handle all of the references to other books.
That happens all over the place, so it would save a lot of work to if
the automation was done better.

I don't see anything wrong with 3.5.4, but my HTML may look
different.

**Comment by Pelonza** [comment]
3.5.4 shows up fine on my desktop...might just have been my laptop.

Here's the latex code for the hint that didn't seem to parse right:

 \item What is the distance from the point $A=(1,2,3)$ to the plane $PQR$.  [Hint: Compute the projection of $\vec {PA}$ onto $\vec n$.  How long is it?] 

---- I think the issue is that the hint showed up on an enumerate line?? ... the "Hint" link showed up in the right place, but the actual HINT didn't get put into the floating box the link opens. (it just showed up after the enumerated list).

-------------
I'm going to go through the tex files and make sure any "Hints" follow this format:
[Hint:  contents ]

-------------
this is separate from all the textbook references (in a different git-hub issue)

**Comment by Pelonza** [comment]
So, I'm looking more closely at the actual MBX file for 3.6.5... and I don't see anything immediately wrong with the formatting. The only thing that might be going on is that it doesn't like the "hint" inside as "statement" object. I might need to dive into the DTD to better understand what's going wrong here... or I might have to think about how things show up for problems...

That said... it seems like it _should_ be ok to include hints on a list item, instead a statement....

**Comment by Pelonza** [comment]
I've now updated all the latex source files to consistently have "hints" formated. All hints that should appear as expandable are formatted with:
[Hint: ---contents -- ]

Note, there is at least twice I still use the WORD 'hint' in undercase... all instances to be linked though are capitalized.

**Comment by Pelonza** [comment]
I think rather than the majority of problems/exercises using the tag `<exercise> </exercise>` this problem can actually be fixed by changing all the tags to:
`<exploration> </exploration>`

I think this will allow any number of `%para` and statement/hint/answer/solutions to be used, which ought to avoid the weird issues with the hints being too late.

**Comment by davidfarmer** [comment]
I hint should not be inside a statement.
If that happens, it can be fixed later.

**Comment by davidfarmer** [comment]
In the neyxt pull request, all the problems and exercises will
be "explorations".

**Comment by Pelonza** [comment]
So... now the hints aren't actually rendering at all. 
But this might be a problem with xsltproc segment faulting, so not finishing parsing those things.

**Comment by Pelonza** [comment]
I take that back... now the hints are not rendering in their knowl's... instead they are rendered as paragraph text afterwards. Is this a problem with PTX ? or XSLT?

**Comment by Pelonza** [comment]
I'm going to assume this is now fixed with tasks implemented.
