### ISSUE TITLE
Preface, not chapter 1

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#5]
All of the contents in "chapter 1" should really be a preface section and/or as part of the front-matter

This might be an issue for me to fix? I.E., relabel that chapter's content or location in the latex files (or directly in the MBX file?)

Related, ideally, Chapter 2 should possibly end up as Chapter 0, or at minimum of Chapter 1. 

@davidfarmer
#2

**Comment by davidfarmer** [comment]
Front matter, prefaces, etc, are always confusing and generally need to be fixed by hand.

This will require learning what the MBX options are, and then changing some tags.

It will not be a lot of work, but it can't be done until the automated conversion is complete.

**Comment by Pelonza** [comment]
I fixed this into a colophon.
