### ISSUE TITLE
In constructing "Problems" replace with "Exercise"

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#8]
This is more of a philosophical issue (and an inclusion thing).
Anything that generates a "Problem" should generate things labeled as "Exercise" not problem.

**Comment by Pelonza** [comment]
@davidfarmer
Tagging you, since this should be easy to fix in the script...

**Comment by davidfarmer** [comment]
Changing 'problem' to 'exercise' in next pull request.  But check if that
functions as expected, because I don't think those environments are
synonyms of each other (but I forget the difference).

**Comment by Pelonza** [comment]
Looking a bit closer at the liveDTD...

It seems that "problem" is a more 'versatile' structure allowing paragraphs again... where as exercise is more limited, but explicitly defines hints, etc. Exercises can also be explicitly numbered (problems can't), exercises can also include webworks problems (problems can't explicitly, but presumably could through the paragraph anyway).

I think exercises are meant to be "inline" where as problems may not be. 

--
All this to say...it seems that replacing with "exercise" didn't break anything I was doing/intending anyway so far....

**Comment by Pelonza** [comment]
Going to close this issue, as it _seems_ to be fine as is... and since it's an environment thing, I _ought_ to be able to just do a find and replace if I really need to down the road.
