### ISSUE TITLE
WolframAlpha link not inserted

### ISSUE THREAD

**Issue by Pelonza** [Pelonza/multivariable-calculus-IBL#9]
There's at least one or multiple places where the macro:
\wolfA 
appears, without having the correct links asserted.

**Comment by davidfarmer** [comment]
\wolfA will be handled after the initial conversion.

**Comment by Pelonza** [comment]
The wolfram alpha inserted link is still off a little. 
It inserts this link:
http//www.wolframalpha.com/
instead of:
http://www.wolframalpha.com/

**Comment by davidfarmer** [comment]
Not sure how that is happening, because when I search the source
I don't find that sequence of characters.

**Comment by Pelonza** [comment]
Yeah.. I'm not finding it in the source either, but I can definitely see the issue on the hosted html...

http://faculty.valpo.edu/calculus3ibl/section-4.html

Expand Exercise 2.1.1

It may just be a result of a bad hyperlink reference of my own, manually inserted... (the search shows http twice there). 

Interesting... in the MBX code I currently have, the \wolfA isn't even rendered as a link:
http://faculty.valpo.edu/calculus3ibl/section-7.html

See example 2.4.1, extra's...

**Comment by Pelonza** [comment]
I fixed the actual typo, and will upload a new mildly changed latex code... 

I'm going to leave this open until the \wolfA is actually rendered as a hyperlink (I removed the spurious link, and replaced with a \wolfA latex macro.)
